Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/VariableNumber:
  # XXX: extremely buggy in v0.43.0
  Enabled: false
Style/SafeNavigation:
  # XXX: extremely buggy in v0.43.0
  Enabled: false
